#coding: utf-8 

import os

def cleanFrame(prjDir,filename):
    srcFile = os.path.join(prjDir+"\descode",filename+'.py')
    # open the file generated by wxformebuilder.
    print(srcFile)
    ptrFile=open(srcFile,'r')
    fbGeneratedCode = ptrFile.read()
    fbGeneratedCode = fbGeneratedCode.replace('animate',"adv")
    fbGeneratedCode = fbGeneratedCode.replace('m_','')
    ptrFile.close()
    # ----- Save src code
    outFile = os.path.join(prjDir+'\src',filename+'.py')
    
    if os.path.exists(outFile):
        ptrFile=open(outFile,"w")
    else:
        ptrFile=open(outFile,"w+")
        
    # write cleaned code to src folder.    
    ptrFile.write(fbGeneratedCode)
    ptrFile.close()

    return 'complete'

prjDir = r"C:\Users\STarikUser\git\wxPyhtonSerialCommunication\SerialCommunicaiton"
filename = "MainFrame"

print('Cleaning descode file: %s' % filename +'.py')
outStat = cleanFrame(prjDir,filename)
print('Clean descode file and save in src folder %s.' % outStat )



